gestaogovbr/Ro-dou

README.md, docker-compose.yml
Este PR resolve a Issue 19. Inclui também uma adição no README.md.
Fix #19
=>  Incluir serviço do selenium no docker-compose.yml

README.md, dag_confs/basic_example_skip_null.yaml, src/dou_dag_generator.py, src/parsers.py, tests/parsers_test.py
=> Criar parâmetro para enviar email

src/dou_dag_generator.py
=> Fix searching terms read from database

.github/workflows/ci-tests.yml, Dockerfile, Makefile, src/dou_dag_generator.py, src/searchers.py
change `from FastETL.` to `from fastetl.` due to library updates
=> update fastetl import

Dockerfile, src/dou_dag_generator.py, src/dou_hook.py, src/searchers.py, src/utils/date.py
- Decrease code coupling by moving DouHook from FastETL provider to folder src. 
- Remove cloning FastETL in build
=> Move DOUhook from FastETL to Ro-dou src

src/searchers.py, tests/searchers_test.py
Special characters must to be considered part of a word in exact search #76
=> change exact search to consider special characters

src/dou_dag_generator.py
- Fix bug on select_terms_from_db task xcom
- Add Taskgroup in xcom_pull
=> Fix select_terms_from_db bug

src/notification/discord_sender.py, src/notification/slack_sender.py, tests/discord_sender_test.py
Add conditional formatting for hiding filters for Slack and Discord notification types.
=> Hide filters for slack and discord

src/report_style.css
- Add css property to justify text in email report.
=> Justify text in email report

src/notification/email_sender.py
Fix format for Outlook email display
=> Fix format for Outlook display

src/parsers.py
in ro-dou yaml `schedule:` key, if it is passed anything other than cron syntax, the dag will consider the string of a Dataset.
To be used with inlabs dag that ingests data for ro-dou.
=> add dataset trigger scheduler

src/hooks/dou_hook.py
Fix pagination when using DOU search and number_pages is exactly 2.
Fix issue #101
=> Fix pagination

src/hooks/inlabs_hook.py, tests/inlabs_hook_test.py
Keep line breaks in the text if full_text is True for better readability, using the **<br>** tag.
=> Keep line breaks in full text mode

src/dou_dag_generator.py
=> Fix logic operators in result_as_html function

src/dou_dag_generator.py, src/parsers.py
- Add syspath for schemas 
- Change dag.owners to string in Dag Generator
=> Add syspath for schemas and change dag.owners to string

.github/workflows/ci-tests.yml
=> Alter trigger to run CI Tests on push only to main branch

src/notification/email_sender.py
Corrige erro no envio de report por email. 
Erro gerado pelo merge dos PR 122 e 118.
=> Hotfix para correção de variável no módulo de envio de email

src/dou_dag_generator.py
Fix #134
Os testes serão objeto de outro PR para tratar a issue #124.
=> Cast tags to a list when generating dags

Dockerfile, docker-compose.yml
=> Upgrade Airflow to 2.10.0

CHANGELOG.md, dag_load_inlabs/ro-dou_inlabs_load_pg_dag.py, src/dou_dag_generator.py
=> Usar validação de data e UI de calendário nos parâmetros das DAGs

src/dou_dag_generator.py
=> reform auto-generated DAG Docs

docs/docs/como_utilizar/habilitacao_docker_no_wsl.md, docs/docs/como_utilizar/instalacao.md, docs/docs/como_utilizar/instalacao_wsl_windows.md
Criando um alerta na documentação para quem deseja instalar o projeto no Windows. Isso pode ser feito através do WSL (Windows Subsystem for Linux).
#194 
@edulauer
=> feat: Adiciona documentação sobre instalação no WSL
