- src/searchers.py
Adiciona um _retry_ à chamada da API para o caso de qualquer eventual erro. Isso vai corrigir um erro de `AttributeError` na leitura do JSON.
> Cria resiliência na chamada da API do DOU

- .github/workflows/ci-tests.yml
- Makefile
- README.md
- dag_confs/dou_qd_example.yaml
- src/dou_dag_generator.py
- src/parsers.py
- src/report_style.css
- src/searchers.py
- tests/conftest.py
- tests/dag_generator_test.py
- tests/parsers_test.py
O Querido Diário é uma plataforma de coleta e indexação dos conteúdos dos Diários Oficiais de vários municípios brasileiros. Com estas mudanças é possível configurar dags para pesquisar também nos conteúdos indexados pelo Querido Diário e no DOU concomitantemente.
Além das mudanças no código fonte também foram adicionadas instruções ao README.
>  Cria opção de pesquisa no Querido Diário

- src/searchers.py
Após as restrições de bots no portal da IN e necessidade de utilização da biblioteca _Selenium_ (#19), as DAGs do Ro-Dou que envolvem busca baseada em lista de servidores têm gerado erros de instabilidade no retorno do _json_ pelo _BeautifulSoap_ através da página de retorno da busca dos termos. 
`    search_results = json.loads(script_tag.contents[0])['jsonArray']
AttributeError: 'NoneType' object has no attribute 'contents'`
Como a função **search_text_with_retry** previa apenas uma tentativa de reexecução da função após um _Exception_, para contornar o problema e permitir a execução completa das DAGs, sugere-se aumentar o número de tentativas de execução da função.
> Adiciona tentativas de execução na função search_text_with_retry

- Makefile
Tests with colored output make it easier to spot errors.
> Make tests run in colored output

- dag_confs/basic_example.yaml
- dag_confs/basic_example_skip_null.yaml
- src/dou_dag_generator.py
- src/parsers.py
- tests/parsers_test.py
Este PR acrescenta a feature para se usar o parâmetro `doc_md` no arquivo de configuração yaml. O conteúdo aceita formatação em *markdown*, que será exibida na opção "DAG Docs"  do Airflow.
Além disso, lá também será informado o nome do arquivo yaml que foi usado para criar a DAG e os parâmetros usados para criá-la, facilitando a sua manutenção.
Inclui também uma correção no id da DAG de exemplo criada para ilustrar o parâmetro `skip_null`, que havia sido criada no PR #24.
Fixes #27 #30
> Implementa feature de documentação markdown e informações úteis

- docker-compose.yml
From the `hooks` folder, only the `dou_hook` module is actually used and mounted as a volume.
However, the `custom_functions` module is mounted as a whole, and other modules may attempt to import modules that are not mounted as volumes in the Ro-DOU container. This causes an import error (see #43).
There are two alternative solutions:
1. Load as volumes in the container all modules under `hooks` from FastETL;
2. be selective and also only mount as a volume the modules used from `custom_functions`.
With this PR, we're opting for solution no. 2.
Fixes #43
> Mount as a volume only the modules used by Ro-DOU

- Dockerfile
- docker-compose.yml
- requirements.txt
So far this project has relied on a docker image used by the ministry dev team, this has limiting the environment customization needed by some ongoing evolutions.
This PR creates an exclusive container to be used by Ro-dou.
Fixes #48
> Decouple this project from the airflow2-docker image

- Dockerfile
- README.md
- docker-compose.yml
This changes the Dockerfile adding some steps to install the Ro-dou src code and FastETL plugin code in build time instead of mapping them as docker volumes.
It simplifies production deployment.
Fix #52
> Bundle src code and plugin into docker image

- .github/workflows/docker_build_and_publish.yml
**Description**
This Pull Request adds a new GitHub Actions workflow file that builds and publishes a Docker image to the GitHub Container Registry. The workflow is triggered by Git tag pushes.
**Changes Made**
- Added a new YAML file to the `.github/workflows/` directory that describes the workflow.
- The workflow consists of several steps that perform actions such as checking out the code, setting up Docker Buildx, logging in to the GitHub Container Registry, and building/pushing the Docker image.
**Reason for Changes**
The reason for creating this workflow is to automate the process of building and publishing Docker images to the GitHub Container Registry whenever a new Git tag is pushed. This will save time and effort for developers who need to build and distribute Docker images. …
> Workflow to build and publish docker image

- dag_confs/examples_and_tests/hide_filters_example.yaml
- schemas/ro-dou.json
- src/notification/email_sender.py
- src/parsers.py
- tests/parsers_test.py
Create boolean parameter **hide_filter** for hiding filter and metadata values, like 'resultados para:', 'filtrando por unidades', date.
Only in email template reporting.
Fix issue #89
> Create param hide_filter

- dag_confs/examples_and_tests/header_and_footer_example.yaml
- schemas/ro-dou.json
- src/notification/discord_sender.py
- src/notification/email_sender.py
- src/notification/slack_sender.py
- src/parsers.py
- tests/discord_sender_test.py
- tests/parsers_test.py
- Add parameters for header and footer text in YAML. 
- Update notification templates in Slack, Discord, and email to support header and footer text.
> Add Header and footer text

- src/notification/email_sender.py
Besides justifying text in the CSS file, for some email clients like Outlook, it is necessary to force justification in the inline HTML tag.
> Force justify text

- dag_confs/examples_and_tests/header_and_footer_example.yaml
- schemas/ro-dou.json
- src/notification/discord_sender.py
- src/notification/email_sender.py
- src/notification/slack_sender.py
- src/parsers.py
- tests/discord_sender_test.py
- tests/parsers_test.py
- Include a parameter for dynamic "no result" text
- Include a variable called **no_results_found_text** in the notification for Email, Slack, and Discord
- Fix the tests
- Add a parameter in the existing example
> Include parameter for dynamic no result text in notification

- src/notification/email_sender.py
Não é estritamente necessário, mas para ficar consistente com o resto do conteúdo do e-mail (que está fechando as tags p).
> Close p tag in watermark

- dag_confs/examples_and_tests/inlabs_advanced_search_example.yaml
- dag_confs/examples_and_tests/inlabs_example.yaml
- dag_load_inlabs/ro-dou_inlabs_load_pg_dag.py
- docs/docs/como_funciona/parametros.md
- schemas/ro-dou.json
- src/dou_dag_generator.py
- src/parsers.py
- tests/dag_generator_test.py
- tests/parsers_test.py
1. Cria um novo parâmetro **dataset** permitindo data-aware schedulling da DAG baseado em dataset e/ou agendamento cron.
2. Atualiza exemplos utilizando o parâmetro dataset.
3. Refatoração: altera e migra as funções utilizada para tratamento de schedule da classe YamlParser para DouDigestDagGenerator
4. Atualiza os testes
5. Atualiza a DAG **ro-dou_inlabs_load_pg_dag.py** incluindo uma task de verificação da carga do dia do INLABS na base da conexão **inlabs_db**
6. Inclui na DAG **ro-dou_inlabs_load_pg_dag.py** um decorator de Short Circuit para interromper a execução da DAG caso não existam arquivos no portal do INLABS para o dia.
> Cria parâmetro para Dataset no Data-Aware Schedulling

- src/dou_dag_generator.py
- src/hooks/inlabs_hook.py
- src/notification/discord_sender.py
- src/notification/email_sender.py
- src/notification/isender.py
- src/notification/slack_sender.py
- src/searchers.py
- tests/conftest.py
- tests/dag_generator_test.py
- tests/discord_sender_test.py
- tests/inlabs_hook_test.py
- tests/searchers_test.py
Agrupa os resultados por unidade no relatório.
- Cria nova função no searches para agrupar os resultados por unidade (department). Cria um nível a mais no dicionário de results para a unidade.
- Altera os senders de email, discord e slack para exibir a unidade quando especificada.
- Altera o INLABS_hook para utilizar o campo artcategory como valor de unidade.
- Atualiza os testes.
- Refatora o código de merge_results
Fix #121
> Agrupar resultados por unidade

- src/notification/email_sender.py
Corrige as linhas e colunas na exportação via CSV, considerando múltiplas buscas.
Fix #117
> Corrige as linhas e colunas na exportação via CSV

- src/dou_dag_generator.py
- src/notification/notifier.py
A partir da versão 2.10 do Airflow foi detectado erro ao chamar múltiplos valores de tasks_ids no xcom_pull.
Código refatorado para fazer o loop entre cada task existente e receber via context e xcom_pull os valores em uma lista.
Fix #139
> Ajusta o código para utilizar XCom_pull de múltiplos Tasks IDs.

- dag_confs/examples_and_tests/qd_list_territory_id_example.yaml
- docs/docs/como_funciona/parametros.md
- schemas/ro-dou.json
- src/schemas.py
- src/searchers.py
- tests/parsers_test.py
- tests/qd_searcher_test.py
Alteração permite busca no querido diário para um grupo de municípios.
Alteração permite passar uma lista de territory_id no DAG;
Alteração não afeta DAGs exitentes que passam apenas um territory_id.
> Permitir busca no QD para um grupo de municípios

- Dockerfile
- Makefile
- dag_load_inlabs/ro-dou_inlabs_load_pg_dag.py
- dag_load_inlabs/sql/init-db.sql
- docker-compose.yml
- docs/docs/como_utilizar/instalacao.md
- Mapeia volume da pasta de logs e da dag do INLABS
- Inclui novas etapas no Makefile para criação do banco local do INLABS e das conexões no Airflow
- Atualiza os providers do Airflow no Dockerfile
- Atualiza o README
fix #155
> Melhorias no deployment local

- dag_confs/examples_and_tests/pubtype_example.yaml
- docs/docs/como_funciona/exemplos.md
- docs/docs/como_funciona/parametros.md
- docs/docs/como_funciona/tipos_de_publicacoes.md
- src/dou_dag_generator.py
- src/hooks/dou_hook.py
- src/hooks/inlabs_hook.py
- src/notification/email_sender.py
- src/schemas.py
- src/searchers.py
- tests/inlabs_searcher_test.py
- tests/parsers_test.py
- tests/searchers_test.py
Cria um novo parâmetro para o search do YAML com o nome de pubtype. O parâmetro permite filtrar os resultados com base no tipo de publicação (Edital, Ata, etc.). O filtro é válido para buscas pelo DOU e INLABS.
- Alterado o parser e searches para o novo parâmetro para sources do DOU e INLABS
- Incluído no template do email os filtros de publicação selecionados
- Atualizado a documentação com o novo parâmetro
- Ajustado os testes para o novo parâmetro e função match_pubtype
- Criado novo exemplo de DAG utilizando o parâmetro pubtype;
Fix #149
> Cria novo parâmetro de filtro por tipo de publicação

- dag_confs/examples_and_tests/department_example.yaml
- docs/docs/como_funciona/parametros.md
- src/dou_dag_generator.py
- src/hooks/dou_hook.py
- src/hooks/inlabs_hook.py
- src/notification/email_sender.py
- src/schemas.py
- src/searchers.py
- tests/inlabs_hook_test.py
- tests/inlabs_searcher_test.py
- tests/parsers_test.py
- tests/searchers_test.py
1. Criar um novo parâmetro chamado **department_ignore** com uma lista de departamentos que serão ignorados na busca. As unidades subordinadas também são ignoradas. Funciona para as fontes **DOU** e **INLabs**.
2. Criar um teste para gerar SQL com department no InlabsHook.
3. Atualizar a documentação com o novo parâmetro.
Fix #169
> Create new parameter department_ignore

- dag_confs/examples_and_tests/qd_example.yaml
- dag_confs/examples_and_tests/qd_list_territory_id_example.yaml
- docs/docs/como_funciona/exemplos.md
- docs/docs/como_funciona/parametros.md
- src/dou_dag_generator.py
- src/schemas.py
- src/searchers.py
- tests/parsers_test.py
- tests/qd_searcher_test.py
resolve #171
Adiciona parâmetros **excerpt_size** e **number_of_excerpts** para buscas no Querido Diário e passa a utilizar o parâmetro **is_exact_search** também nas consultas ao Querido Diário.
A possibilidade de não usar o termo exato permite a utilização de buscas avançadas no Querido Diário.
Também foi incluída lógica para alterar a quantidade de registros padrão nas respostas das requisições em que se utliza uma lista de territory_ids. 
Em uma busca, por exemplo, em todos os municípios de um Estado que possua mais de 100 cidades, o novo código retornará todos os resultados, mesmo que o resutado seja superior ao padrão de 100 registros.
A alteração ainda remove parâmetros não utilizados no método QDSearcher.exec_search
> Adiciona novos parâmetros para o QD
